// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Gestion_Inventario.Data;

#nullable disable

namespace Sistema_Gestion_Inventario.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251010153211_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.Almacen", b =>
                {
                    b.Property<int>("IdAlmacen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlmacen"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAlmacen");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Almacen_Codigo");

                    b.ToTable("Almacen", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categoria_Nombre");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.MovimientoInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("int");

                    b.Property<int?>("IdOrdenCompraDetalle")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioOperador")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("Motivo")
                        .HasColumnType("smallint");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("FechaMovimiento")
                        .HasDatabaseName("IX_MovInv_FechaMovimiento");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdOrdenCompraDetalle");

                    b.HasIndex("IdUsuarioOperador");

                    b.HasIndex("IdProducto", "IdAlmacen")
                        .HasDatabaseName("IX_MovInv_ProductoAlmacen");

                    b.ToTable("MovimientoInventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_MovInv_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_MovInv_CompraRequiere_IN_y_OCDet", "(Motivo <> 1 OR (Tipo = 'IN' AND IdOrdenCompraDetalle IS NOT NULL))");

                            t.HasCheckConstraint("CK_MovInv_CostoNoNeg", "(CostoUnitario IS NULL OR CostoUnitario >= 0)");

                            t.HasCheckConstraint("CK_MovInv_Motivo", "[Motivo] IN (1,2,3,4,5,6,7,8)");

                            t.HasCheckConstraint("CK_MovInv_Tipo", "[Tipo] IN ('IN','OUT')");
                        });
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.OrdenCompra", b =>
                {
                    b.Property<int>("IdOrdenCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdenCompra"));

                    b.Property<short>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEsperada")
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("IdAlmacenRecepcion")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("ARS")
                        .IsFixedLength();

                    b.Property<string>("NumeroOc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NumeroOC");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdOrdenCompra");

                    b.HasIndex("IdAlmacenRecepcion");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("NumeroOc")
                        .IsUnique()
                        .HasDatabaseName("UQ_OrdenCompra_NumeroOC");

                    b.ToTable("OrdenCompra", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrdenCompra_Estado", "[Estado] IN (0,1,2,3,4)");

                            t.HasCheckConstraint("CK_OrdenCompra_Moneda", "[Moneda] IN ('ARS','USD','EUR')");
                        });
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.OrdenCompraDetalle", b =>
                {
                    b.Property<int>("IdOrdenCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdenCompraDetalle"));

                    b.Property<decimal>("CantidadPedida")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CantidadRecibida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DescuentoPct")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("IdOrdenCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal?>("ImpuestoPct")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdOrdenCompraDetalle");

                    b.HasIndex("IdOrdenCompra")
                        .HasDatabaseName("IX_OCDet_IdOrdenCompra");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("IX_OCDet_IdProducto");

                    b.ToTable("OrdenCompraDetalle", null, t =>
                        {
                            t.HasCheckConstraint("CK_OCDet_Cantidades", "(CantidadPedida > 0 AND CantidadRecibida >= 0)");

                            t.HasCheckConstraint("CK_OCDet_Costos", "(CostoUnitario >= 0)");

                            t.HasCheckConstraint("CK_OCDet_Porcentajes", "((ImpuestoPct IS NULL OR (ImpuestoPct >= 0 AND ImpuestoPct <= 100)) AND (DescuentoPct IS NULL OR (DescuentoPct >= 0 AND DescuentoPct <= 100)))");
                        });
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CostoStd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdProveedorPrincipal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecioSugerido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdProducto");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasDatabaseName("UX_Producto_CodigoBarras_NotNull")
                        .HasFilter("[CodigoBarras] IS NOT NULL");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProveedorPrincipal");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UQ_Producto_SKU");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cp")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CP");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CUIT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("LeadTimeDias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdProveedor");

                    b.HasIndex("Cuit")
                        .IsUnique()
                        .HasDatabaseName("UQ_Proveedor_CUIT");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Proveedor_Email_NotNull")
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.MovimientoInventario", b =>
                {
                    b.HasOne("Sistema_Gestion_Inventario.Data.Almacen", "IdAlmacenNavigation")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdAlmacen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MovInv_Almacen");

                    b.HasOne("Sistema_Gestion_Inventario.Data.OrdenCompraDetalle", "IdOrdenCompraDetalleNavigation")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdOrdenCompraDetalle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_MovInv_OCDet");

                    b.HasOne("Sistema_Gestion_Inventario.Data.Producto", "IdProductoNavigation")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MovInv_Producto");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuarioOperador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_MovInv_Usuario");

                    b.Navigation("IdAlmacenNavigation");

                    b.Navigation("IdOrdenCompraDetalleNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.OrdenCompra", b =>
                {
                    b.HasOne("Sistema_Gestion_Inventario.Data.Almacen", "IdAlmacenRecepcionNavigation")
                        .WithMany("OrdenesRecepcion")
                        .HasForeignKey("IdAlmacenRecepcion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_OrdenCompra_AlmacenRecepcion");

                    b.HasOne("Sistema_Gestion_Inventario.Data.Proveedor", "IdProveedorNavigation")
                        .WithMany("OrdenesCompra")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OrdenCompra_Proveedor");

                    b.Navigation("IdAlmacenRecepcionNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.OrdenCompraDetalle", b =>
                {
                    b.HasOne("Sistema_Gestion_Inventario.Data.OrdenCompra", "IdOrdenCompraNavigation")
                        .WithMany("Detalles")
                        .HasForeignKey("IdOrdenCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrdenCompraDetalle_OC");

                    b.HasOne("Sistema_Gestion_Inventario.Data.Producto", "IdProductoNavigation")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OrdenCompraDetalle_Producto");

                    b.Navigation("IdOrdenCompraNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.Producto", b =>
                {
                    b.HasOne("Sistema_Gestion_Inventario.Data.Categoria", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Categoria");

                    b.HasOne("Sistema_Gestion_Inventario.Data.Proveedor", "IdProveedorPrincipalNavigation")
                        .WithMany("ProductosPrincipales")
                        .HasForeignKey("IdProveedorPrincipal")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Producto_ProveedorPrincipal");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdProveedorPrincipalNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.Almacen", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("OrdenesRecepcion");
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.OrdenCompra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.OrdenCompraDetalle", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.Producto", b =>
                {
                    b.Navigation("DetallesCompra");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Sistema_Gestion_Inventario.Data.Proveedor", b =>
                {
                    b.Navigation("OrdenesCompra");

                    b.Navigation("ProductosPrincipales");
                });
#pragma warning restore 612, 618
        }
    }
}
